Added post process function for copy operation

diff --git a/gdmarp b/gdmarp
--- a/gdmarp
+++ b/gdmarp
@@ -7,6 +7,7 @@ init_var(){
 	out_dir="$PWD"/build
 	cache_dir="$PWD"/cache
 	out_name="out"
+	final_name=""
 	include=""
 	sources=""
 	flag_purgemode=none
@@ -16,6 +17,7 @@ init_var(){
 	flag_init_git=false
 	flag_format=""
 	flag_modules=""
+	flag_copy_to=""
 	flag_input_file="index.gddt"
 	flag_prep_norestore=false
 	only_prep=false
@@ -36,7 +38,7 @@ marp=marp
 # FUNCTIONS
 
 help_message(){
-	echo "$bin_name - Compile markdown file into pptx file with predefined macro support."
+	echo "$bin_name - generate various game design documents formats from single gddt file"
 	echo "Usage: gdmarp <subcommand> [options]"
 	echo " "
 	echo "options:"
@@ -46,6 +48,7 @@ help_message(){
 	echo "-M <module>           a module to include with execution"
 	echo "-P <MODE>             give a purge mode {all|user|var}"
 	echo "-O <file name>        designate a file name for final result"
+	echo "-C <directory path>   copy built result into given directory"
 	echo "-g                    initiate with git after gdmarp init and create a gitignore file"
 	echo "-h                    show brief help"
 	echo "-n                    do not apply default macro rules"
@@ -181,7 +184,8 @@ gd_preprocess(){
 		# If this is prep subcommand then set file's name to given name
 		# Other than out_file should be in root directory
 		if [ "$only_prep" = "true" ]; then
-			mv "$out_file" -f "$out_dir"/$out_name.gddt
+			final_name="$out_dir"/$out_name.gddt
+			mv "$out_file" -f "$final_name"
 		else
 			# Out_file should be in root directory, so don't move but copy
 			cp -f "$out_file" "$cache_dir"
@@ -192,6 +196,13 @@ gd_preprocess(){
 	fi
 }
 
+gd_postprocess(){
+	# Copy file to given directory
+	if ! [ -z "$flag_copy_to" ]; then
+		cp "$final_name" "$flag_copy_to"
+	fi
+}
+
 gd_repr(){
 	# Preprocessing before marp compilation
 	gd_preprocess
@@ -199,13 +210,15 @@ gd_repr(){
 	# Change out.gddt to out.md because marp expects markdown file
 	mv "$out_file" out.md
 
+	final_name="$out_dir"/$out_name.$flag_format
+
 	# Compile with marp-cli
 	if [ "$flag_use_docker" = "false" ]; then
 		# No Docker
-		$marp --allow-local-files --$flag_format --html out.md -o "$out_dir"/$out_name.$flag_format
+		$marp --allow-local-files --$flag_format --html out.md -o "$final_name"
 	else
 		# With Docker
-		docker run --rm --init -v "$cwd":/home/marp/app/ -e LANG="$LANG" marpteam/marp-cli out.md --$flag_format --allow-local-files --html -o "$out_dir"/$out_name.$flag_format
+		docker run --rm --init -v "$cwd":/home/marp/app/ -e LANG="$LANG" marpteam/marp-cli out.md --$flag_format --allow-local-files --html -o "$final_name"
 	fi
 
 	if [ "$flag_preserve" = "false" ]; then
@@ -242,8 +255,10 @@ gd_wiki(){
 			# No need to remove file because out_file is the file that should
 			# be sent and it is natural to save final result
 
+			final_name="$out_dir"/$out_name.wikitext
+
 			# Change name to given final name and save to 
-			mv "$out_file" -f "$out_dir"/$out_name.wikitext
+			mv "$out_file" -f "$final_name"
 			;;
 		*)
 			echo "No proper module was given to render a wiki page"
@@ -269,6 +284,8 @@ gd_wui(){
 			# so that all texts within out.gddt will be ignored in final html file
 			sed -i -e '1 i\divert(`-1\x27)' -e '$a\divert`\x27' "$out_file"
 
+			final_name="$out_dir"/"$out_name".html
+
 			# Process macros, kind of template engine
 			# This doesn't uitilze webui's macro because it is not used internally
 			# however this might change in the future, who knows
@@ -277,10 +294,10 @@ gd_wui(){
 			"$MODULE"/webui/bts/env.m4 "$cwd"/env.m4 \
 			"$bin_path"/m4/default.m4 "$out_file" \
 			"$MODULE"/webui/bts/template/main.html | awk -f \
-			"$SCRIPTS"/rmExtNewLines.awk > "$out_dir"/"$out_name".html
+			"$SCRIPTS"/rmExtNewLines.awk > "$final_name"
 
 			# Restore escaped characters
-			sed -i -f "$SCRIPTS"/restore.sed "$out_dir"/"$out_name".html
+			sed -i -f "$SCRIPTS"/restore.sed "$final_name"
 
 			# Remove middle file because preserve flag would have already saved
 			# copy in cache
@@ -321,15 +338,18 @@ gd_dial(){
 					# m4 run again to include file inside of index.html file
 					m4 -I "$cwd" -I "$bin_path"/modules/dialogue/gdlogue/template "$bin_path"/modules/dialogue/gdlogue/template/index.html > "$out_dir"/"$out_name".html
 
+					final_name="$out_dir"/"$out_name".html 
 					# Restore escaped characters 
 					# This is mostly for es6 string literal syntax <``> 
-					sed -i -f "$SCRIPTS"/restore.sed "$out_dir"/"$out_name".html
+					sed -i -f "$SCRIPTS"/restore.sed "$final_name"
 					;;
 				pdf)
-					dot -Tpdf out.gv -o "$out_dir"/"$out_name".pdf
+					final_name="$out_dir"/"$out_name".pdf
+					dot -Tpdf out.gv -o "$final_name"
 					;;
 				png)
-					dot -Gdpi=300 -Tpng out.gv -o "$out_dir"/"$out_name".png
+					final_name="$out_dir"/"$out_name".png
+					dot -Gdpi=300 -Tpng out.gv -o "$final_name"
 					;;
 			esac
 
@@ -561,6 +581,16 @@ gd_main(){
 				fi
 				shift
 				;;
+			-C) # Copy to
+				if [ -n "$2" ]; then
+					flag_copy_to=$2
+					shift
+				else
+					printf 'ERROR: "-C" requires a non-empty option argument.\n' >&2
+					exit 1
+				fi
+				shift
+				;;
 			-F) # Format
 				if [ -n "$2" ]; then
 					case "$2" in
@@ -639,8 +669,8 @@ gd_main(){
 		esac
 	done
 	$action
+	gd_postprocess
 	[ "$action" = "" ] && echo "No proper subcommand was given"
-	#exit 0
 }
 
 # ----------
